import type { ElementType } from 'react';
import { Activity, CloudRain, Gauge, Minus, Plus, Wind } from 'lucide-react';
import { Area, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { models } from '@/data/mock';
import { buildBlend, buildForecastSeries } from '@/lib/blending';
import { useScenario } from '@/lib/scenario-context';
import { Caveat, Kpi, SectionHeading } from '@/components/Charts';
import { PageFrame } from './PageFrame';

export default function Forecast() {
  const { scenario } = useScenario();
  const result = buildBlend(scenario);
  const series = buildForecastSeries(scenario);
  return <PageFrame eyebrow="02 / forecast comparison" title="Compare the forecast before you commit." description="A common horizon makes model disagreement visible. ATMASYN is shown alongside the six contributing systems so an operator can see the spread, not just a single number.">
    <div className="grid gap-4 sm:grid-cols-3"><Kpi label="Selected horizon" value={`${scenario.leadTime}h`} detail={`${scenario.variable} · ${scenario.regime}`} accent icon={Gauge} /><Kpi label="Blend output" value={`${result.forecast.rainfall} mm`} detail="accumulated rainfall · demo" icon={CloudRain} /><Kpi label="Model spread" value={`±${result.uncertainty}%`} detail="illustrative uncertainty estimate" icon={Activity} /></div>
    <section className="panel p-4 sm:p-5"><SectionHeading eyebrow="Horizon view / 24h → 168h" title="Rainfall accumulation and model spread" detail="Values are normalized to the selected variable; illustrative only." action={<div className="mono text-[10px] text-[hsl(var(--muted-foreground))]">mm · DEMO DATA</div>} /><div className="h-[360px] w-full" data-testid="chart-forecast-comparison"><ResponsiveContainer width="100%" height="100%"><LineChart data={series.map((item, index) => ({ horizon: `${item.horizon}h`, blend: item.blend.rainfall, lower: Math.max(0, item.blend.rainfall - item.spread), upper: item.blend.rainfall + item.spread, gfs: Math.max(2, Math.round(item.blend.rainfall * (.72 + ((models[0].id.length + index * 3) % 17) / 50))), ifs: Math.max(2, Math.round(item.blend.rainfall * (.76 + ((models[1].id.length + index * 3) % 17) / 50))), aifs: Math.max(2, Math.round(item.blend.rainfall * (.81 + ((models[2].id.length + index * 3) % 17) / 50))), icon: Math.max(2, Math.round(item.blend.rainfall * (.7 + ((models[3].id.length + index * 3) % 17) / 50))), bharatfs: Math.max(2, Math.round(item.blend.rainfall * (.84 + ((models[4].id.length + index * 3) % 17) / 50))) }))} margin={{ top: 12, right: 16, left: 0, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="horizon" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} axisLine={false} tickLine={false} width={36} /><Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 4, fontSize: 11 }} /><Legend wrapperStyle={{ fontSize: 11 }} /><Area type="monotone" dataKey="upper" stroke="none" fill="#0e8b79" fillOpacity={0.08} name="Uncertainty envelope" /><Area type="monotone" dataKey="lower" stroke="none" fill="hsl(var(--background))" fillOpacity={1} name="" /><Line type="monotone" dataKey="gfs" stroke={models[0].color} strokeWidth={1.5} dot={false} name="GFS" /><Line type="monotone" dataKey="ifs" stroke={models[1].color} strokeWidth={1.5} dot={false} name="ECMWF IFS" /><Line type="monotone" dataKey="aifs" stroke={models[2].color} strokeWidth={1.5} dot={false} name="ECMWF AIFS" /><Line type="monotone" dataKey="icon" stroke={models[3].color} strokeWidth={1.5} dot={false} name="ICON" /><Line type="monotone" dataKey="bharatfs" stroke={models[4].color} strokeWidth={1.5} dot={false} name="BharatFS" /><Line type="monotone" dataKey="blend" stroke={models[5].color} strokeWidth={3} dot={{ r: 3 }} name="ATMASYN Blend" /></LineChart></ResponsiveContainer></div><p className="mt-2 text-[10px] text-[hsl(var(--muted-foreground))]">Illustrative uncertainty estimate derived from inter-model spread and historical-error prior.</p></section>
    <div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]">
    <section className="panel p-4 sm:p-5"><SectionHeading eyebrow="Selected forecast" title={`What the blend says at ${scenario.leadTime}h`} /><div className="grid grid-cols-3 gap-3"><Datum icon={CloudRain} label="RAIN" value={`${result.forecast.rainfall} mm`} /><Datum icon={Activity} label="TEMP" value={`${result.forecast.temperature} °C`} /><Datum icon={Wind} label="WIND" value={`${result.forecast.wind} m/s`} /></div><div className="mt-6 flex items-center gap-2 border-t border-[hsl(var(--border))] pt-4 text-xs"><span className="rounded bg-[hsl(var(--primary))] px-2 py-1 font-semibold text-[hsl(var(--primary-foreground))]">ATMASYN</span><span className="text-[hsl(var(--muted-foreground))]">weighted output across five model priors</span></div></section>
      <section className="panel p-4 sm:p-5"><SectionHeading eyebrow="Reading the chart" title="Disagreement is a signal." /><ul className="space-y-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]"><li className="flex gap-2"><Plus size={14} className="mt-0.5 text-[hsl(var(--primary))]" /> Longer lead time lowers confidence and widens the illustrative envelope.</li><li className="flex gap-2"><Minus size={14} className="mt-0.5 text-[hsl(var(--accent))]" /> A model can lead in one regime and lose in another.</li></ul></section>
    </div><Caveat>Forecast comparison is a visual reasoning aid. No live NWP files or observations are connected in this prototype.</Caveat>
  </PageFrame>;
}
function Datum({ icon: Icon, label, value }: { icon: ElementType; label: string; value: string }) { return <div className="rounded border border-[hsl(var(--border))] p-3"><Icon size={15} className="text-[hsl(var(--primary))]" /><p className="eyebrow mt-3 text-[hsl(var(--muted-foreground))]">{label}</p><p className="mono mt-1 text-lg">{value}</p></div>; }