import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CheckCircle2, FlaskConical, Info } from 'lucide-react';
import { baseSkill, models } from '@/data/mock';
import { useScenario } from '@/lib/scenario-context';
import { buildBlend } from '@/lib/blending';
import { Caveat, SectionHeading } from '@/components/Charts';
import { PageFrame } from './PageFrame';

export default function Verification() {
  const { scenario } = useScenario();
  const result = buildBlend(scenario);
  const chartData = baseSkill.map((skill) => ({
    model: models.find((item) => item.id === skill.modelId)?.shortName,
    rmse: skill.rmse,
    ets: skill.ets,
  }));

  return <PageFrame eyebrow="04 / verification" title="Skill is a question, not a claim." description="This view establishes the evaluation frame for ATMASYN. Values are illustrative placeholders until hindcast runs are connected to observations.">
    <div className="grid gap-4 sm:grid-cols-3"><div className="panel flex items-start gap-3 p-4"><FlaskConical size={18} className="text-[hsl(var(--accent))]" /><div><p className="eyebrow text-[hsl(var(--muted-foreground))]">Validation state</p><p className="mt-1 text-sm font-semibold">Pending observation run</p></div></div><div className="panel flex items-start gap-3 p-4"><CheckCircle2 size={18} className="text-[hsl(var(--primary))]" /><div><p className="eyebrow text-[hsl(var(--muted-foreground))]">Metrics shown</p><p className="mt-1 text-sm font-semibold">RMSE + ETS</p></div></div><div className="panel flex items-start gap-3 p-4"><Info size={18} className="text-[hsl(var(--primary))]" /><div><p className="eyebrow text-[hsl(var(--muted-foreground))]">Current context</p><p className="mt-1 text-sm font-semibold">{scenario.regime} · {result.leadTime}h</p></div></div></div>
    <section className="panel p-4 sm:p-5"><SectionHeading eyebrow="Illustrative metric board" title="Cross-model comparison" detail="Lower RMSE is better · higher ETS is better" /><div className="overflow-x-auto"><table className="w-full min-w-[650px] border-collapse text-left" data-testid="table-verification"><thead><tr className="border-b border-[hsl(var(--border))] text-[10px] text-[hsl(var(--muted-foreground))]"><th className="px-3 py-3 font-medium">MODEL</th><th className="px-3 py-3 font-medium">TYPE</th><th className="px-3 py-3 font-medium">RMSE <span className="mono">(mm)</span></th><th className="px-3 py-3 font-medium">ETS</th><th className="px-3 py-3 font-medium">STATUS</th></tr></thead><tbody>{baseSkill.map((skill) => { const model = models.find((item) => item.id === skill.modelId); return <tr key={skill.modelId} className={`border-b border-[hsl(var(--border)/.7)] text-xs ${skill.modelId === 'blend' ? 'bg-[hsl(var(--primary)/.06)] font-semibold' : ''}`} data-testid={`row-skill-${skill.modelId}`}><td className="px-3 py-3"><span className="mr-2 inline-block h-2 w-2 rounded-full" style={{ backgroundColor: model?.color }} />{model?.name}</td><td className="px-3 py-3 text-[hsl(var(--muted-foreground))]">{model?.type}</td><td className="px-3 py-3 mono">{skill.rmse.toFixed(1)}</td><td className="px-3 py-3 mono">{skill.ets.toFixed(2)}</td><td className="px-3 py-3"><span className="rounded border border-[hsl(var(--border))] px-1.5 py-1 text-[9px] text-[hsl(var(--muted-foreground))]">{skill.status}</span></td></tr>; })}</tbody></table></div></section>
    <div className="grid gap-5 lg:grid-cols-2">
      <section className="panel p-4 sm:p-5" data-testid="chart-rmse"><SectionHeading eyebrow="RMSE comparison" title="Lower is better" /><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="model" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} axisLine={false} tickLine={false} width={32} /><Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 4, fontSize: 11 }} /><Bar dataKey="rmse" fill="#0e8b79" radius={[3, 3, 0, 0]} name="RMSE" /></BarChart></ResponsiveContainer></div></section>
      <section className="panel p-4 sm:p-5" data-testid="chart-ets"><SectionHeading eyebrow="ETS comparison" title="Higher is better" /><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartData} margin={{ top: 8, right: 12, left: 0, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" /><XAxis dataKey="model" tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 0.8]} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 11 }} axisLine={false} tickLine={false} width={32} /><Tooltip contentStyle={{ backgroundColor: 'hsl(var(--card))', border: '1px solid hsl(var(--border))', borderRadius: 4, fontSize: 11 }} /><Bar dataKey="ets" fill="#d28b3c" radius={[3, 3, 0, 0]} name="ETS" /></BarChart></ResponsiveContainer></div></section>
    </div>
    <div className="grid gap-5 lg:grid-cols-[1fr_.75fr]"><section className="panel p-4 sm:p-5"><SectionHeading eyebrow="Method note" title="What will be verified next?" /><div className="space-y-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{['Align forecast cut-offs across all contributing systems.', 'Score against IMD station observations and GPM-IMERG precipitation estimates.', 'Stratify by region, season, lead time, and weather regime before fitting weights.'].map((text, index) => <div key={text} className="flex gap-3"><span className="mono flex h-5 w-5 shrink-0 items-center justify-center rounded bg-[hsl(var(--secondary))] text-[10px] text-[hsl(var(--primary))]">0{index + 1}</span><span>{text}</span></div>)}</div></section><section className="panel border-[hsl(var(--accent)/.5)] bg-[hsl(var(--accent)/.06)] p-4 sm:p-5"><p className="eyebrow text-[hsl(var(--accent))]">Caveat / महत्वपूर्ण</p><h2 className="mt-2 text-lg font-semibold">Validation pending</h2><p className="mt-2 text-xs leading-5 text-[hsl(var(--muted-foreground))]">The apparent blend improvement is not a proven result. It is a placeholder to show how model skill can be compared transparently.</p></section></div><Caveat>Explicit validation-pending caveat: do not use these values for live operational decisions.</Caveat>
  </PageFrame>;
}