import { useState } from 'react';
import { ArrowDown, Check, ChevronRight, Database, GitMerge, LineChart, ScanSearch, SlidersHorizontal } from 'lucide-react';
import { useScenario } from '@/lib/scenario-context';
import { buildBlend } from '@/lib/blending';
import { Caveat, SectionHeading } from '@/components/Charts';
import { PageFrame } from './PageFrame';

const stages = [
  { id: 'ingest', number: '01', title: 'Ingest & align', icon: Database, copy: 'Bring model fields and observations onto a common grid, cut-off, and lead-time axis.', detail: 'Inputs: GFS · IFS · AIFS · ICON · BharatFS · IMD observations · GPM-IMERG' },
  { id: 'diagnose', number: '02', title: 'Diagnose context', icon: ScanSearch, copy: 'Classify region, season, lead time, variable, and weather regime before scoring.', detail: 'Context: regional climatology · regime flag · lead-time decay · missingness check' },
  { id: 'weight', number: '03', title: 'Adapt weights', icon: SlidersHorizontal, copy: 'Apply the MVP inverse-error / skill-weighted engine and preserve the reason for every adjustment.', detail: 'Output: normalized model contributions with a rationale trace' },
  { id: 'blend', number: '04', title: 'Blend & expose', icon: GitMerge, copy: 'Produce a weighted forecast, uncertainty estimate, and operational alert cues for a human decision.', detail: 'Output: ATMASYN forecast · confidence · uncertainty · agreement' },
  { id: 'verify', number: '05', title: 'Verify later', icon: LineChart, copy: 'Score the system against observations and recalibrate priors before claiming skill.', detail: 'Pending: hindcast archive · RMSE · ETS · reliability by regime' },
];

export default function Workflow() {
  const [open, setOpen] = useState('weight');
  const { scenario } = useScenario();
  const result = buildBlend(scenario);
  return <PageFrame eyebrow="06 / operational workflow" title="From many forecasts to one accountable blend." description="The workflow keeps model diversity visible while making the final recommendation legible to a human operator. Click a stage to inspect its contract.">
    <section className="panel p-4 sm:p-6"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow text-[hsl(var(--primary))]">Pipeline / 05 stages</p><h2 className="mt-1 text-lg font-semibold">Operational forecast blending workflow</h2></div><div className="rounded border border-[hsl(var(--primary)/.35)] bg-[hsl(var(--primary)/.06)] px-3 py-2"><p className="eyebrow text-[hsl(var(--primary))]">Current run</p><p className="mono mt-1 text-xs">{scenario.regionId} / {scenario.leadTime}h</p></div></div><div className="space-y-2">{stages.map((stage, index) => { const Icon = stage.icon; const isOpen = open === stage.id; return <div key={stage.id}><button type="button" onClick={() => setOpen(isOpen ? '' : stage.id)} className={`flex w-full items-center gap-3 rounded border p-3 text-left transition-colors ${isOpen ? 'border-[hsl(var(--primary)/.5)] bg-[hsl(var(--primary)/.06)]' : 'border-[hsl(var(--border))] hover:bg-[hsl(var(--muted)/.5)]'}`} data-testid={`button-workflow-${stage.id}`}><span className="mono w-7 text-xs text-[hsl(var(--muted-foreground))]">{stage.number}</span><span className={`flex h-8 w-8 items-center justify-center rounded ${isOpen ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]'}`}><Icon size={15} /></span><span className="flex-1"><span className="block text-sm font-semibold">{stage.title}</span><span className="mt-0.5 block text-[11px] text-[hsl(var(--muted-foreground))]">{stage.copy}</span></span><ChevronRight size={15} className={`transition-transform ${isOpen ? 'rotate-90' : ''}`} /></button>{isOpen && <div className="ml-[67px] flex items-center gap-2 border-l border-[hsl(var(--primary)/.35)] px-4 py-3 text-[11px] text-[hsl(var(--muted-foreground))]"><Check size={14} className="text-[hsl(var(--primary))]" />{stage.detail}</div>}{index < stages.length - 1 && <div className="ml-[28px] h-2 border-l border-dashed border-[hsl(var(--border))]" />}</div>; })}</div></section>
    <section className="panel p-4 sm:p-5"><SectionHeading eyebrow="Adaptive weight engine / current output" title="Readable in one glance" detail="Every output keeps its context attached." /><div className="grid gap-3 md:grid-cols-4">{[['INPUTS', `${scenario.season} · ${scenario.regime}`, 'Region, season, regime, horizon'], ['METHOD', 'Inverse-error', 'Skill-weighted MVP'], ['LEADER', result.weights[0]?.modelId?.toUpperCase() ?? 'IFS', `${result.weights[0]?.weight}% illustrative weight`], ['OUTPUT', `${result.confidence}%`, `confidence · ±${result.uncertainty}% uncertainty`]].map(([label, value, detail]) => <div key={String(label)} className="rounded border border-[hsl(var(--border))] p-3"><p className="eyebrow text-[hsl(var(--muted-foreground))]">{label}</p><p className="mono mt-2 text-sm font-medium">{value}</p><p className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{detail}</p></div>)}</div><div className="mt-5 flex justify-center text-[hsl(var(--muted-foreground))]"><ArrowDown size={17} /></div></section><Caveat>The architecture is a prototype workflow. Integration, hindcast validation, calibration, and production monitoring remain required before operational use.</Caveat>
  </PageFrame>;
}